-- Reproducible support for real campaign launches and notification storage.

create table if not exists public.notificaciones (
  id bigint generated by default as identity primary key,
  id_usuario integer not null,
  titulo text not null,
  mensaje text,
  tipo text not null default 'info' check (tipo in ('info', 'alerta', 'exito')),
  leida boolean not null default false,
  id_campania text,
  accion_url text,
  created_at timestamptz not null default now()
);

create index if not exists notificaciones_usuario_created_idx
  on public.notificaciones (id_usuario, created_at desc);

create index if not exists notificaciones_usuario_leida_idx
  on public.notificaciones (id_usuario, leida);

create or replace function public.activate_campaign(p_campaign_id text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id text;
  v_campaign_name text;
  v_carrera_id text;
  v_success bool := false;
  v_generated_count int := 0;
begin
  select id_campania, nombre, id_carrera
  into v_campaign_id, v_campaign_name, v_carrera_id
  from public.campanias_evaluacion
  where id_campania = p_campaign_id;

  if v_campaign_id is null then
    return json_build_object(
      'success', false,
      'message', 'Campaign not found',
      'generated_count', 0
    );
  end if;

  insert into public.asignaciones_evaluacion (
    id_campania,
    id_docente,
    id_asignatura,
    estado
  )
  select
    p_campaign_id,
    d.id_docente,
    d.id_asignatura,
    'pendiente'::text
  from public.designaciones d
  inner join public.asignaturas a on d.id_asignatura = a.id_asignatura
  where (v_carrera_id is null or a.id_carrera = v_carrera_id)
  and not exists (
    select 1
    from public.asignaciones_evaluacion ae
    where ae.id_campania = p_campaign_id
    and ae.id_docente = d.id_docente
    and ae.id_asignatura = d.id_asignatura
  )
  on conflict (id_campania, id_docente, id_asignatura)
  do nothing;

  select count(*)::int into v_generated_count
  from public.asignaciones_evaluacion
  where id_campania = p_campaign_id;

  update public.campanias_evaluacion
  set estado = 'activa'
  where id_campania = p_campaign_id;

  insert into public.notificaciones (
    id_usuario,
    titulo,
    mensaje,
    tipo,
    id_campania,
    accion_url
  )
  select distinct
    u.id_usuario,
    'Nueva campania de evaluacion',
    'Tiene una evaluacion docente pendiente para la campania ' || coalesce(v_campaign_name, p_campaign_id) || '.',
    'info',
    p_campaign_id,
    '/evaluacion-docente'
  from public.asignaciones_evaluacion ae
  inner join public.usuarios u on u.id_docente::text = ae.id_docente::text
  where ae.id_campania = p_campaign_id
  and not exists (
    select 1
    from public.notificaciones n
    where n.id_usuario = u.id_usuario
    and n.id_campania = p_campaign_id
    and n.accion_url = '/evaluacion-docente'
  );

  v_success := true;

  return json_build_object(
    'success', v_success,
    'message', 'Campaign activated successfully',
    'generated_count', v_generated_count,
    'campaign_id', p_campaign_id
  );
exception
  when others then
    return json_build_object(
      'success', false,
      'message', SQLERRM,
      'generated_count', 0
    );
end;
$$;

create or replace function public.lanzar_campania(
  p_nombre text,
  p_fecha_limite date,
  p_creada_por integer,
  p_semestre integer,
  p_anio integer
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id_campania text;
  v_result json;
begin
  if exists (
    select 1
    from public.campanias_evaluacion
    where estado = 'activa'
  ) then
    raise exception 'YA_EXISTE_CAMPANIA_ACTIVA';
  end if;

  v_id_campania := 'campania-' || p_anio || '-' || p_semestre || '-' || floor(extract(epoch from clock_timestamp()))::bigint;

  insert into public.campanias_evaluacion (
    id_campania,
    nombre,
    estado,
    fecha_inicio,
    fecha_fin,
    descripcion,
    id_carrera
  )
  values (
    v_id_campania,
    p_nombre,
    'borrador',
    current_date,
    p_fecha_limite,
    'semestre:' || p_semestre || '; anio:' || p_anio || '; creada_por:' || p_creada_por,
    null
  );

  v_result := public.activate_campaign(v_id_campania);

  if coalesce((v_result->>'success')::boolean, false) is false then
    raise exception '%', coalesce(v_result->>'message', 'No se pudo activar la campania');
  end if;

  return v_id_campania;
end;
$$;

grant execute on function public.activate_campaign(text) to authenticated;
grant execute on function public.activate_campaign(text) to anon;
grant execute on function public.lanzar_campania(text, date, integer, integer, integer) to authenticated;
grant execute on function public.lanzar_campania(text, date, integer, integer, integer) to anon;
